; ESP32 Motor + Engel Koruyucu Firmware
; Derleme: pio run
; Yükleme: pio run --target upload

[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
upload_resetmethod = nodemcu
